// File generated by FlutterFire CLI.
// ignore_for_file: type=lintщ
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ivCmSqqQCocNOmGJqqBpzpAr7VM9hzE',
    appId: '1:479804461302:web:240cc998852a652e1e9cd7',
    messagingSenderId: '479804461302',
    projectId: 'car-rent-8dde7',
    authDomain: 'car-rent-8dde7.firebaseapp.com',
    storageBucket: 'car-rent-8dde7.firebasestorage.app',
    measurementId: 'G-DQJ0SWZ512',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxLR7Y3mtnZeTx3SLmSR0o0S4GAxc_e8',
    appId: '1:479804461302:android:fce20bc4bab2759e1e9cd7',
    messagingSenderId: '479804461302',
    projectId: 'car-rent-8dde7',
    storageBucket: 'car-rent-8dde7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ivCmSqqQCocNOmGJqqBpzpAr7VM9hzE',
    appId: '1:479804461302:web:30f85f4dde8778701e9cd7',
    messagingSenderId: '479804461302',
    projectId: 'car-rent-8dde7',
    authDomain: 'car-rent-8dde7.firebaseapp.com',
    storageBucket: 'car-rent-8dde7.firebasestorage.app',
    measurementId: 'G-33GW60MB6C',
  );
}
